### ISSUE TITLE
Scripts that cache opds feeds don't work when an oauth provider is enabled

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/circulation#231]
```
Traceback (most recent call last):
  File "bin/cache_opds_lane_facets", line 11, in <module>
    CacheFacetListsPerLane().run()
  File "/Users/amyslagle/dev/circulation/scripts.py", line 304, in __init__
    super(CacheRepresentationPerLane, self).__init__()
  File "/Users/amyslagle/dev/circulation/scripts.py", line 266, in __init__
    app.manager = CirculationManager(self._db)
  File "/Users/amyslagle/dev/circulation/api/controller.py", line 143, in __init__
    self.opds_authentication_document = self.auth.create_authentication_document()
  File "/Users/amyslagle/dev/circulation/api/authenticator.py", line 175, in create_authentication_document
    authenticate=provider.authenticate_url(),
  File "/Users/amyslagle/dev/circulation/api/clever.py", line 40, in authenticate_url
    redirect_uri = url_for('oauth_callback', _external=True)
  File "/Users/amyslagle/dev/circulation/env/lib/python2.7/site-packages/flask/helpers.py", line 258, in url_for
    raise RuntimeError('Attempted to generate a URL without the '
RuntimeError: Attempted to generate a URL without the application context being pushed. This has to be executed when application context is available.
```

**Comment by aslagle** [comment]
This works in https://github.com/NYPL-Simplified/circulation/pull/285
