### ISSUE TITLE
Error borrowing 3M books on QA

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/circulation#338]
I'm getting an error borrowing 3M books on QA.
http://qa.circulation.librarysimplified.org/works/3M/3M%20ID/apfqz89/borrow
and 
http://qa.circulation.librarysimplified.org/works/3M/3M%20ID/dx4rcg9/borrow

This isn't happening on production so it could be related to the decorators I just added.

This is the exception:
Traceback (most recent call last):
  File "/var/lib/app/env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/lib/app/env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/app/env/local/lib64/python2.7/site-packages/newrelic-2.56.0.42/newrelic/hooks/framework_flask.py", line 40, in _nr_wrapper_handler_
    return wrapped(*args, **kwargs)
  File "/var/lib/app/env/local/lib/python2.7/site-packages/flask_cors/decorator.py", line 127, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "./api/routes.py", line 96, in decorated
    return f(*args, **kwargs)
  File "./core/app_server.py", line 167, in decorated
    v = f(*args, **kwargs)
  File "./api/routes.py", line 198, in borrow
    return app.manager.loans.borrow(data_source, identifier_type, identifier, mechanism_id)
  File "./api/controller.py", line 588, in borrow
    patron, pin, pool, mechanism
  File "./api/circulation.py", line 227, in borrow
    patron, pin, licensepool, internal_format
  File "./api/threem.py", line 145, in checkout
    response = self.request('checkout', body, method="PUT")
  File "./core/threem.py", line 170, in request
    allow_redirects=False
  File "./core/threem.py", line 200, in _request_with_timeout
    return HTTP.request_with_timeout(method, url, *args, **kwargs)
  File "./core/util/http.py", line 143, in request_with_timeout
    url, requests.request, http_method, url, *args, **kwargs
  File "./core/util/http.py", line 163, in _request_with_timeout
    response = m(*args, **kwargs)
  File "/var/lib/app/env/local/lib64/python2.7/site-packages/newrelic-2.56.0.42/newrelic/api/external_trace.py", line 124, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/var/lib/app/env/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/var/lib/app/env/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/var/lib/app/env/local/lib64/python2.7/site-packages/newrelic-2.56.0.42/newrelic/api/external_trace.py", line 124, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/var/lib/app/env/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/var/lib/app/env/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/var/lib/app/env/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/var/lib/app/env/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/var/lib/app/env/local/lib64/python2.7/site-packages/newrelic-2.56.0.42/newrelic/hooks/external_httplib.py", line 53, in httplib_endheaders_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib64/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 897, in _send_output
    self.send(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 869, in send
    self.sock.sendall(data)
  File "/var/lib/app/env/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 216, in sendall
    data = memoryview(data)
TypeError: cannot make memory view because object does not have the buffer interface

**Comment by aslagle** [comment]
It's also possible this is related to https://github.com/NYPL-Simplified/server_core/issues/361.

I haven't been able to reproduce it locally or on circulation alpha.

**Comment by leonardr** [comment]
This looks like an interaction between Unicode data and the SSL library. We're going to try deploying a fix to core.
