### ISSUE TITLE
Someone isn't checking to see if `load_pagination_from_request` returns a ProblemDetail

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/circulation#351]
I believe this is the request that causes the problem:

GET /works/series/Tin%20Star?available=now&after=50&order=author&collection=main&size=50

```
Traceback (most recent call last):
  File "/var/lib/app/env/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/lib/app/env/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/app/env/local/lib64/python2.7/site-packages/newrelic-2.66.0.49/newrelic/hooks/framework_flask.py", line 40, in _nr_wrapper_handler_
    return wrapped(*args, **kwargs)
  File "./core/app_server.py", line 167, in decorated
    v = f(*args, **kwargs)
  File "./api/routes.py", line 239, in series
    return app.manager.work_controller.series(series_name)
  File "./api/controller.py", line 945, in series
    pagination=load_pagination_from_request()
  File "./api/opds.py", line 130, in feed_url
    kwargs.update(dict(facets.items()))
AttributeError: 'ProblemDetail' object has no attribute 'items'
```

**Comment by leonardr** [comment]
I can't duplicate the 500 error on production or locally, but I do see what the problem is.
