### ISSUE TITLE
3M sync failure makes it look like patron has no 3M books

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/circulation#412]
3M sometimes gives bad results that crash the XML parser during a sync:

```
Traceback (most recent call last):
  File "/var/lib/app/circulation/core/scripts.py", line 490, in do_run
    provider.run()
  File "/var/lib/app/circulation/core/coverage.py", line 114, in run
    self.run_once_and_update_timestamp()
  File "/var/lib/app/circulation/core/coverage.py", line 123, in run_once_and_update_timestamp
    offset, count_as_covered=BaseCoverageRecord.ALL_STATUSES
  File "/var/lib/app/circulation/core/coverage.py", line 195, in run_once
    self.process_batch_and_handle_results(batch)
  File "/var/lib/app/circulation/core/coverage.py", line 235, in process_batch_and_handle_results
    results = self.process_batch(batch)
  File "/var/lib/app/circulation/core/coverage.py", line 765, in process_batch
    result = self.process_item(identifier)
  File "/var/lib/app/circulation/core/threem.py", line 439, in process_item
    metadata = self.api.bibliographic_lookup(identifier, max_age=0)
  File "/var/lib/app/circulation/core/threem.py", line 191, in bibliographic_lookup
    response = list(self.item_list_parser.parse(data))
  File "/var/lib/app/circulation/core/threem.py", line 260, in parse
    for i in self.process_all(xml, "//Item"):
  File "/var/lib/app/circulation/core/util/xmlparser.py", line 55, in process_all
    root = etree.parse(StringIO(xml), parser)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:85131)
  File "src/lxml/parser.pxi", line 1799, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:124241)
  File "src/lxml/parser.pxi", line 1819, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:124533)
  File "src/lxml/parser.pxi", line 1707, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:123074)
  File "src/lxml/parser.pxi", line 1079, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:117114)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:110510)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:112276)
  File "src/lxml/parser.pxi", line 624, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:111367)
XMLSyntaxError: None
```

When this happens, the patron's 3M loans and holds should be left alone. Instead, they're removed entirely from the local side, and they stay gone until the patron successfully completes a sync with 3M.

**Comment by leonardr** [comment]
Amy fixed this.
