### ISSUE TITLE
Error when searching lane that defers to top-level parent

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/circulation#53]
```
Traceback (most recent call last):
  File "/var/lib/app/env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/lib/app/env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/app/env/local/lib/python2.7/site-packages/newrelic-2.54.0.41/newrelic/hooks/framework_flask.py", line 40, in _nr_wrapper_handler_
    return wrapped(*args, **kwargs)
  File "./app.py", line 69, in decorated
    v = f(*args, **kwargs)
  File "./app.py", line 105, in lane_search
    return app.manager.opds_feeds.search(languages, lane_name)
  File "./controller.py", line 505, in search
    query=query, annotator=annotator
  File "./core/opds.py", line 649, in search
    results = search_lane.search(query, search_engine, limit)
  File "./core/lane.py", line 1038, in search
    search_lane = get_searchable_lane(self)
  File "./core/lane.py", line 1035, in get_searchable_lane
    logging.debug("Lane %s is not searchable; using parent %s" % (lane.name, lane.parent.name))
AttributeError: 'NoneType' object has no attribute 'name'
in get_searchable_lane
    logging.debug("Lane %s is not searchable; using parent %s" % (lane.name, lane.parent.name))
AttributeError: 'NoneType' object has no attribute 'name'
```

This needs to handle the case where lane is None or lane.parent is None

**Comment by leonardr** [comment]
https://github.com/NYPL-Simplified/server_core/pull/45
