### ISSUE TITLE
There's a 3M book that breaks the loans feed

### ISSUE THREAD

**Issue by aslagle** [NYPL-Simplified/circulation#55]
Placing the book "Fates and Furies" by Lauren Groff on hold breaks the loans feed on circulation alpha:

Traceback (most recent call last):
  File "/home/ec2-user/circulation/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/circulation/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/circulation/env/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/hooks/framework_flask.py", line 40, in _nr_wrapper_handler_
    return wrapped(*args, **kwargs)
  File "/home/ec2-user/circulation/app.py", line 63, in decorated
    return f(*args, **kwargs)
  File "/home/ec2-user/circulation/app.py", line 69, in decorated
    v = f(*args, **kwargs)
  File "/home/ec2-user/circulation/app.py", line 117, in active_loans
    return app.manager.loans.sync()
  File "/home/ec2-user/circulation/controller.py", line 541, in sync
    self.circulation, patron)
  File "/home/ec2-user/circulation/opds.py", line 511, in active_loans_for
    work = hold.license_pool.work or hold.license_pool.edition.work
AttributeError: 'NoneType' object has no attribute 'work'

On production, it doesn't throw an exception, but the hold doesn't show up in the feed. 

I haven't been able to find any other books that cause this problem.

**Comment by aslagle** [comment]
I found another one: "What Belongs to You" by Garth Greenwell. I think these are books that were recently added to the collection.

**Comment by leonardr** [comment]
Did you put these books on hold through Simplified or through the 3M app?

**Comment by aslagle** [comment]
Through 3M. They don't show up in Simplified.

**Comment by leonardr** [comment]
aha, cool

**Comment by leonardr** [comment]
I see this problem with 3M identifiers "hso7989" and "guddqz9" in your account. These books have LicensePools but no Edition and no Work. The identifiers have no CoverageRecord, which means we haven't gone to the metadata wrangler for them yet. This might just be a result of the current backlog, or it could indicate a deeper problem or just that something else isn't running that should be.

In such a case the OPDS feed should either not show the book, or show it as a book we don't have information about yet.
