### ISSUE TITLE
service_status controller is broken

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/circulation#619]
Error report:

```
017-08-03 16:22:01,430:root:ERROR:app_server.py:Exception in web app: 'Request' object has no attribute 'library'
Traceback (most recent call last):
  File "/var/www/circulation/env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/circulation/env/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/circulation/core/app_server.py", line 179, in decorated
    v = f(*args, **kwargs)
  File "/var/www/circulation/api/routes.py", line 414, in service_status
    return app.manager.service_status()
  File "/var/www/circulation/api/controller.py", line 1328, in __call__
    library = flask.request.library
  File "/var/www/circulation/env/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'library'
```

This might be the time to move the entire service_status controller into the admin interface. The catch is it's useful to have unauthenticated access to this controller for monitoring purposes.

**Comment by leonardr** [comment]
The controller is no longer broken, but long-term it needs to be moved into the admin interface.
